In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Retail_Dataset_Modified (1).csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [4]:
df.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [5]:
df.sample(5)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
2076,BX_DELHI_068,BrandX_India Electronics Delhi,BrandX_India,Express,Delhi,Metro,Samsung Tab S8,Electronics,Tablets,Discontinued,...,76.3,84.1,Aggressive,Low,5.0,111,3,2023,Q1,Summer
3512,BX_HYDERABAD_071,BrandX_India Style Hyderabad,BrandX_India,Street Store,Hyderabad,Metro,Nike Jacket,Clothes,Jackets,Growing,...,84.8,89.7,Aggressive,Medium,4.0,105,1,2024,Q1,Spring
2838,BX_CHENNAI_055,BrandX_India Accessories Chennai,BrandX_India,Street Store,Chennai,Metro,Samsung Galaxy Watch,Gadgets,Smart Watches,Declining,...,98.1,89.6,Aggressive,Low,2.0,121,9,2023,Q3,Monsoon
3986,BX_SURAT_021,BrandX_India Living Surat,BrandX_India,Mall Store,Surat,Tier2,Blue Star 1 Ton,Home Appliances,Air Conditioners,Mature,...,86.6,64.3,Standard,High,5.0,323,5,2024,Q2,Summer
5126,BX_MUMBAI_086,BrandX_India Fresh Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sunflower Oil 1L,Groceries,Oil,Mature,...,92.7,85.3,Aggressive,Low,2.0,145,8,2024,Q3,Monsoon

In [7]:
print("Columns in Dataset:")
print(df.columns)

Columns in Dataset:
Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [8]:
print("Data Types:")
print(df.dtypes)

Data Types:
Store_ID                  object
Store_Name                object
Brand_Name                object
Store_Type                object
City                      object
City_Tier                 object
Product_Name              object
Category                  object
Sub_Category              object
Product_Stage             object
Quantity_Available        object
Units_Sold                object
Unit_Price                 int64
Cost_Price                 int64
Revenue                   object
Profit_Margin            float64
Average_Order_Value        int64
Inventory_Turnover       float64
Days_of_Stock              int64
Customer_Segment          object
Sales_Channel             object
Payment_Method            object
Supplier                  object
Supplier_Rating           object
Promotion_Type            object
Promotion_Impact         float64
Max_Discount_Offered       int64
Return_Rate              float64
Return_Reason             object
Customer_Satisfaction    float64
Online_Rating            float64
Review_Count               int64
Sales_Rep_Experience       int64
Sales_Rep_Rating         float64
Market_Share             float64
Competition_Level         object
Competitor_Count           int64
Brand_Loyalty            float64
Brand_Awareness          float64
Price_Competitiveness     object
Weather_Impact            object
Delivery_Time            float64
Shipping_Cost             object
Month                      int64
Year                       int64
Quarter                   object
Season                    object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   object
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: float64(11), int64(10), object(26)
memory usage: 1.9+ MB

In [10]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [11]:
print(df['Category'].unique())

['Groceries' 'Clothes' 'Gadgets' 'Electronics' 'Home Appliances'
 'ELECTRONICS' '  Groceries  ' 'home appliances' 'HOME APPLIANCES'
 '  Electronics  ' 'gadgets' 'groceries' 'electronics'
 '  Home Appliances  ' 'clothes' '  Gadgets  ' 'GROCERIES' '  Clothes  '
 'GADGETS' 'CLOTHES']

In [12]:
print(df['Category'].value_counts())

Category
Electronics            1295
Clothes                1290
Gadgets                1017
Groceries              1006
Home Appliances         503
  Electronics             8
electronics               6
CLOTHES                   5
gadgets                   4
groceries                 4
HOME APPLIANCES           4
ELECTRONICS               4
GROCERIES                 4
home appliances           3
  Groceries               3
  Home Appliances         3
  Gadgets                 3
clothes                   3
  Clothes                 3
GADGETS                   3
Name: count, dtype: int64

In [13]:
selected_columns = df[['Revenue','Units_Sold','Profit_Margin']]
print(selected_columns.head())

   Revenue Units_Sold  Profit_Margin
0     7320         24          21.64
1     1645         35          29.79
2    66340         31          19.86
3    77748         22          18.11
4  1976364         39          20.15

In [14]:
print(df.iloc[0])

Store_ID                                  BX_PUNE_034
Store_Name               BrandX_India Superstore Pune
Brand_Name                               BrandX_India
Store_Type                                   Flagship
City                                             Pune
City_Tier                                       Tier1
Product_Name                           Green Tea 100g
Category                                    Groceries
Sub_Category                                      Tea
Product_Stage                               Declining
Quantity_Available                                125
Units_Sold                                         24
Unit_Price                                        305
Cost_Price                                        239
Revenue                                          7320
Profit_Margin                                   21.64
Average_Order_Value                               432
Inventory_Turnover                                2.3
Days_of_Stock                                     156
Customer_Segment                               Budget
Sales_Channel                     BrandX_India Online
Payment_Method                                    UPI
Supplier                  BrandX_India E-commerce Hub
Supplier_Rating                                   Nan
Promotion_Type                         Festival Offer
Promotion_Impact                                 23.1
Max_Discount_Offered                                9
Return_Rate                                       3.1
Return_Reason                              Wrong Size
Customer_Satisfaction                             4.0
Online_Rating                                     4.6
Review_Count                                       53
Sales_Rep_Experience                                5
Sales_Rep_Rating                                  4.8
Market_Share                                     15.3
Competition_Level                              Medium
Competitor_Count                                    8
Brand_Loyalty                                    70.8
Brand_Awareness                                  75.7
Price_Competitiveness                        Standard
Weather_Impact                                    Low
Delivery_Time                                     6.0
Shipping_Cost                                      57
Month                                               1
Year                                             2022
Quarter                                            Q1
Season                                         Spring
Name: 0, dtype: object

In [15]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(5171, 47)

In [16]:
high_price = df[df['Unit_Price'] > 1000]
high_price[['Product_Name', 'Category', 'Unit_Price']].head()

     Product_Name     Category  Unit_Price
2  Levi's T-Shirt      Clothes        2140
3   Adidas Hoodie      Clothes        3534
4   PlayStation 5      Gadgets       50676
6   PlayStation 5      Gadgets       51299
7  MacBook Air M2  Electronics      103410

In [17]:
low_price = df[df['Unit_Price'] < 500]
low_price[['Product_Name', 'Category', 'Unit_Price']].head()

        Product_Name   Category  Unit_Price
0     Green Tea 100g  Groceries         305
1    White Sugar 1kg  Groceries          47
5       Toor Dal 1kg  Groceries         173
11   Olive Oil 500ml  Groceries         377
17  Sunflower Oil 1L  Groceries         173

In [18]:
medium_price = df[
    (df['Unit_Price'] >= 500) &
    (df['Unit_Price'] <= 1500)
]
medium_price[['Product_Name', 'Category', 'Unit_Price']].head()

        Product_Name   Category  Unit_Price
9     H&M Cotton Tee    Clothes         808
21  Basmati Rice 5kg  Groceries         659
38    H&M Cotton Tee    Clothes        1015
43    H&M Cotton Tee    Clothes        1269
44    H&M Cotton Tee    Clothes        1059

In [19]:
sorted_price = df.sort_values(
    by='Unit_Price',
    ascending=False
)
sorted_price[['Product_Name', 'Category', 'Unit_Price']].head()

          Product_Name Category  Unit_Price
2458  Sony Alpha a7 IV  Gadgets      307651
4584  Sony Alpha a7 IV  Gadgets      306035
4765  Sony Alpha a7 IV  Gadgets      305722
1099  Sony Alpha a7 IV  Gadgets      305634
2820  Sony Alpha a7 IV  Gadgets      305536

In [20]:
top_price = df.nlargest(10, 'Unit_Price')
print(top_price[['Unit_Price']])

      Unit_Price
2458      307651
4584      306035
4765      305722
1099      305634
2820      305536
2134      304378
3658      304251
3880      303095
718       302841
1065      302473

In [21]:
print("Number of Products with Unit Price > 1000:")
print(len(high_price))

Number of Products with Unit Price > 1000:
4127