In [6]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("/content/Retail_Dataset_Cleaned.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [ ]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [ ]:
df.info()

In [10]:
segment_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Customer_Segment",
    aggfunc="sum"
)

segment_revenue

                       Revenue
Customer_Segment
Budget            1.712615e+09
Luxury            1.863606e+09
Mid-Range         1.822548e+09
Premium           1.683088e+09

In [11]:
category_summary = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc=["sum", "mean", "max", "min"]
)
category_summary

                          sum          mean         max       min
                      Revenue       Revenue     Revenue   Revenue
Category
Clothes          2.220630e+08  1.717425e+05   1245972.0    4985.0
Electronics      3.623063e+09  2.769926e+06  11182353.0  120655.0
Gadgets          2.654379e+09  2.594701e+06  23343582.0    9295.0
Groceries        2.394028e+07  2.365641e+04    350176.0     840.0
Home Appliances  5.584119e+08  1.094925e+06   6588592.0   81333.0

In [12]:
channel_summary = pd.pivot_table(
    df,
    values="Revenue",
    index="Sales_Channel",
    aggfunc=["sum", "mean"]
)
channel_summary

                                       sum          mean
                                   Revenue       Revenue
Sales_Channel
Brandx_India App              1.397363e+09  1.357982e+06
Brandx_India Online           1.414593e+09  1.395062e+06
Brandx_India Phone Order      1.394133e+09  1.376242e+06
Brandx_India Social Commerce  1.390170e+09  1.409908e+06
Brandx_India Store            1.485598e+09  1.345650e+06

In [13]:
city_performance = pd.pivot_table(
    df,
    values=["Revenue", "Profit_Margin"],
    index="City",
    aggfunc={
        "Revenue": "sum",
        "Profit_Margin": "mean"
    }
)
city_performance

               Profit_Margin       Revenue
City
Ahmedabad          22.624845  2.655276e+08
Bangalore          22.830374  8.407997e+08
Bhopal             22.620614  1.079895e+08
Chennai            22.259758  7.419116e+08
Delhi              22.282928  1.661122e+09
Hyderabad          22.239853  6.597958e+08
Jaipur             22.326377  2.670945e+08
Kanpur             22.539515  8.430218e+07
Lucknow            22.070538  9.486221e+07
Mumbai             22.435763  1.674840e+09
Nagpur             22.342162  7.479879e+07
Pune               22.756934  2.936829e+08
Surat              22.883691  2.340634e+08
Visakhapatnam      22.574245  8.106636e+07

In [14]:
store_summary = pd.pivot_table(
    df,
    values=["Revenue", "Profit_Margin"],
    index="Store_Type",
    aggfunc="sum"
)
store_summary

              Profit_Margin       Revenue
Store_Type
Express            22687.78  1.438936e+09
Flagship           23531.50  1.413566e+09
Mall Store         23780.07  1.492527e+09
Online Hub         22713.13  1.442170e+09
Street Store       22806.53  1.294659e+09

In [20]:
store_name = pd.pivot_table(
    df,
    values=["Profit_Margin"],
    index=["Store_Name"],
    aggfunc="sum"
)
store_name

                                    Profit_Margin
Store_Name
Brandx_India Accessories Ahmedabad         418.89
Brandx_India Accessories Bangalore         533.39
Brandx_India Accessories Bhopal            207.98
Brandx_India Accessories Chennai           539.95
Brandx_India Accessories Delhi            1390.12
...                                           ...
Brandx_India Trends Mumbai                1420.74
Brandx_India Trends Nagpur                 207.20
Brandx_India Trends Pune                   351.48
Brandx_India Trends Surat                  391.28
Brandx_India Trends Visakhapatnam          132.57

[280 rows x 1 columns]

In [19]:
product_name = pd.pivot_table(
    df,
    values=["Quantity_Available"],
    index=["Product_Name"],
    aggfunc="sum"
)
product_name

                      Quantity_Available
Product_Name
Adidas Hoodie                    17949.0
Adidas Ultraboost                15156.0
Airpods Pro                      17673.0
Anker Powercore                  15901.0
Apple Watch Series 8             14523.0
Aquaguard Crystal                 6692.0
Basmati Rice 5Kg                 16486.0
Blue Star 1 Ton                   8613.0
Bosch 6Kg Top Load                7944.0
Bose Soundlink                   15231.0
Brown Rice 1Kg                   16724.0
Brown Sugar 500G                 16554.0
Canon Eos R6                     12912.0
Daikin 1.5 Ton Split              6184.0
Dell Xps 13                      17040.0
Forever 21 Dress                 14612.0
Green Tea 100G                   21847.0
H&M Cotton Tee                   20409.0
Hp Pavilion                      16275.0
Ifb 7Kg Front Load                6009.0
Ipad Pro                         15274.0
Iphone 14                        13619.0
Jbl Charge 5                     12579.0
Kent Grand Plus                   5639.0
Levi'S 511 Jeans                 13877.0
Levi'S T-Shirt                   17732.0
Lg 28L Convection                 7729.0
Lg Double Door 260L               7919.0
Lg Oled 55Inch                   15776.0
Macbook Air M2                   14743.0
Mi Power Bank                    15098.0
Moong Dal 1Kg                    17072.0
Nike Air Max                     30120.0
Nike Jacket                      12685.0
Olive Oil 500Ml                  15286.0
Oneplus 11                       13815.0
Pepe Jeans                       14063.0
Playstation 5                    13315.0
Samsung 23L Solo                  6958.0
Samsung Galaxy S23               16606.0
Samsung Galaxy Watch             11937.0
Samsung Side By Side              6322.0
Samsung Tab S8                   17202.0
Sony Alpha A7 Iv                 16398.0
Sony Bravia 43Inch               10546.0
Sony Wh-1000Xm5                  17554.0
Sunflower Oil 1L                 18358.0
Tata Tea Premium                 19120.0
Toor Dal 1Kg                     19458.0
White Sugar 1Kg                  17047.0
Xbox Series X                    16078.0
Zara Casual Shirt                14055.0
Zara Evening Dress               16559.0